year_col = 'year'
month_col = 'month'
day_col = 'day'
hour_col = 'hour'
weekday_col = 'weekday'
temp_col = 'temp'
function_col = 'function'
is_weekend_col = 'is_weekend'
is_prev_weekend_col = 'is_prev_weekend'
is_next_weekend_col = 'is_next_weekend'
workhour_col = 'is_workhour'
season_col = 'season'
blackout_col = 'blackout'
phases_col = 'phases'
deenergized_col = 'deenergized'

country = 'UA'
csv_delim = ';'